checkpoint_file = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/prune_cosine_restarts/pruned_models/41.pt"
output_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/prune_cosine_restarts/inferences/41"

[model]
img_size = 256
patch_size = 4
tubelet_size = 2
in_chans = 2
encoder_embed_dim = 192
encoder_depth = 4
encoder_num_heads = 4
decoder_embed_dim = 96
decoder_depth = 4
decoder_num_heads = 4
mlp_ratio = 4.0
num_frames = 2
num_out_frames = 1
patch_recovery = "subpixel_conv"

[dataset]
data_dir = "/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1/"
frame_range = [350000, 353004] # (start_frame, start_frame + (inference_length * target_step) + target_step)
target_step = 3
stride = 3
num_frames = 2

[inference]
inference_length = 750000
