[analysis]
inference_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/prune_cosine_restarts/inferences/41_chunked/"
output_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/prune_cosine_restarts/long_analysis/41"
img_size = 256

analysis_length = 750000
temporal_mean = true
zonal_mean = true
zonal_eof_pc = true
eof_ncomp = 3
PC_autocorr_nlags = 300
div = true
spectra = true
return_period = true
return_period_anomaly = true # ?
PDF_U = false # ? 
PDF_Omega = false # ? 
