# checkpoint_file = "/glade/derecho/scratch/jshen/2d-turbulence-vit/BASE/pruning_checkpoints/iteration_7.pt"
# output_file = "/glade/derecho/scratch/jshen/2d-turbulence-vit/BASE/pruning_checkpoints/analyses/iteration_base_metrics.npz"

checkpoint_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/prune_plateau_early_stop/pruned_models"
output_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/prune_plateau_early_stop/short_analysis/"

[model]
img_size = 256
patch_size = 4
tubelet_size = 2
in_chans = 2
encoder_embed_dim = 192
encoder_depth = 4
encoder_num_heads = 4
decoder_embed_dim = 96
decoder_depth = 4
decoder_num_heads = 4
mlp_ratio = 4.0
num_frames = 2
num_out_frames = 1
patch_recovery = "subpixel_conv"

[test_dataset]
data_dir = "/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1/"
frame_range = [350000, 353600]
target_step = 3
stride = 3
num_frames = 2

[climo_dataset]
data_dir = "/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1/"
frame_range = [350000, 351000]
target_step = 1
stride = 1
num_frames = 1

[analysis]
max_leadtime = 100
n_ensembles = 10
