[model]
# Model architecture parameters (should match training config)
in_channels = 2
d_embed = 128
n_heads = 8
n_layers = 8
img_shape = [256, 256]
patch_shape = [4, 4]
checkpoint_path = "/path/to/your/model/checkpoint.pth"

[train_dataset]
# Training dataset configuration (for compatibility with analysis functions)
data_dir = "/path/to/your/training/data"
frame_ranges = [[200000, 210000]]
target_offset = 3

[test_dataset]
# Test dataset configuration
data_dir = "/path/to/your/test/data"
frame_ranges = [[350000, 360000]]
target_offset = 3

[evaluation]
spectra_leadtimes = [0, 5, 10, 99]
batch_size = 32
analysis_length = 100
num_ensembles = 10

# Climatology configuration (optional)
[evaluation.climatology]
data_dir = "/path/to/your/climatology/data"
frame_ranges = [[200000, 210000]]
target_offset = 3
batch_size = 1000 