dataset_params:
  run_num: "base"
  root_dir: "/ocean/projects/phy220045p/jakhar/2d_emulator_vision/SSL-for-2D-Turbulence/results/BASE/"
  model_filename: "training_checkpoints/best_ckpt.tar"
  params_filename: "hyperparams.yaml"

short_analysis_params:
# on the fly analysis - plots are saved
  rmse: !!bool True
  acc: !!bool True
  spectra: !!bool True
  spectra_leadtimes: [0, 5, 10, 99]
  analysis_length: 100 # number of training timesteps
  num_ensembles: 10
  test_file_start_idx: 350000
  test_length_climo: 1000
  plot_analysis: !!bool True
  save_short_analysis: !!bool True
  
long_analysis_params:
# For Train: Details would be taken from training config file
  long_analysis_train: !!bool True

# For Truth
  long_analysis_truth: !!bool True
  truth_file_range: [200000, 300000]

# For emualtor
  long_analysis_emulator: !!bool True
# Data would be saved to perform any long analysis for emulator
  save_data_length: 1000 # number of training timesteps emulated and saved
  analysis_length: 1000 # number of training timesteps emulated for analysis (
  # For Training data analysis_length is the smaller value in between analysis_length vs training_length

# Analysis
  temporal_mean: !!bool True
  zonal_mean: !!bool True
  zonal_eof: !!bool True
  eof_ncomp: 3
  div: !!bool True
  return_period: !!bool True
  PDF: !!bool False # U, Omega This may need large memory to compute
  video: !!bool True
  video_length: 1000

