[model]
img_size = 256
patch_size = 4
num_frames = 2
tubelet_size = 2
in_chans = 2
encoder_embed_dim = 192
encoder_depth = 4
encoder_num_heads = 4
decoder_embed_dim = 96
decoder_depth = 4
decoder_num_heads = 4
mlp_ratio = 4.0
num_out_frames = 1
patch_recovery = 'subpixel_conv'

[train_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
file_range = [ [200000, 210000], [995000, 1004997], ]
target_step = 3
train_tendencies = false
stride = 1
num_frames = 2
num_out_frames = 1
target_step_hist = 3

[validation_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
file_range = [ [310000, 312000], ]
target_step = 3
train_tendencies = false
stride = 1
num_frames = 2
num_out_frames = 1
target_step_hist = 3

[training]
learning_rate = 0.0005
weight_decay = 1e-7
warmup_start_factor = 0.001
warmup_epochs = 3
plateau_factor = 0.2
plateau_patience = 5
epochs = 1000
batch_size = 32
checkpoint_period = 5
output_dir = '/glade/derecho/scratch/jshen/pruning-turbulence-vit/train/'