[model]
in_channels = 2
d_embed = 128
n_heads = 4
n_layers = 8
img_shape = [ 256, 256,]
patch_shape = [ 8, 8,]

[train_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_ranges = [ [200000, 210000], [995000, 1004997], ]
target_offset = 3

[validation_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_ranges = [ [310000, 312000], ]
target_offset = 3

[training]
learning_rate = 0.0005
weight_decay = 1e-7
warmup_start_factor = 0.001
warmup_epochs = 3
plateau_factor = 0.2
plateau_patience = 5
epochs = 1000
batch_size = 32
checkpoint_period = 5
output_dir = '/glade/derecho/scratch/jshen/pruning-turbulence-vit/train/'