checkpoint_file = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/best.tar"
output_file = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/metrics.npz"

[model]
img_size = 256
patch_size = 4
tubelet_size = 2
in_chans = 2
encoder_embed_dim = 192
encoder_depth = 4
encoder_num_heads = 4
decoder_embed_dim = 96
decoder_depth = 4
decoder_num_heads = 4
mlp_ratio = 4.0
num_frames = 2
num_out_frames = 1
patch_recovery = "subpixel_conv"

[test_dataset]
data_dir = "/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1/"
file_range = [350000, 353599] # [test_start, test_start + (max_leadtime * (n_ensembles + 2) * target_step) - 1]
target_step = 3
stride = 3
num_frames = 2
num_out_frames = 1
train_tendencies = false

[climo_dataset]
data_dir = "/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1/"
file_range = [350000, 351000]
target_step = 1
stride = 1
num_frames = 1
num_out_frames = 1
train_tendencies = false

[analysis]
max_leadtime = 100 # number of training timesteps
n_ensembles = 10
