data_dir: 
  /glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1/
exp_dir: /glade/derecho/scratch/dpatel/SSL-2DTurb/
init_seed: '0'
log_to_screen: 'True'
log_to_wandb: 'True'
wandb_table_logging_interval: '25'
project: SSL-2DTurb
group: Dhruvit-base-emulator
name: BASE_seed_0_2phase_1000epochs
diagnostic_logs: 'True'
fresh_start: 'True'
early_stopping: 'False'
save_checkpoint: 'True'
ckpt_epoch_list: '[25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350,
  375, 400, 425, 450, 475, 500, 600, 700, 800, 900, 1000]'
train_file_range: '[[200000, 210000], [995000, 1004997]]'
valid_file_range: '[310000, 312000]'
batch_size: '4'
target_step: '3'
num_workers: '8'
pin_memory: 'True'
optimizer_type: AdamW
gpu: 'True'
lr: '0.0005'
scheduler: ReduceLROnPlateau
warmup: 'True'
warmup_startfactor: '0.001'
warmup_totaliters: '3'
weight_decay: '1e-07'
max_epochs: '1000'
checkpointing: 'False'
integrator: None
spectral_loss: 'False'
spectral_loss_weight: '1'
spectral_loss_threshold_wavenumber: '50'
train_tendencies: 'False'
img_shape: '[256, 256]'
img_size: '256'
patch_size: '4'
patch_shape: '[4, 4]'
num_frames: '2'
tubelet_size: '2'
in_chans: '2'
encoder_embed_dim: '192'
encoder_depth: '4'
encoder_num_heads: '4'
decoder_embed_dim: '96'
decoder_depth: '4'
decoder_num_heads: '4'
mlp_ratio: '4.0'
num_out_frames: '1'
patch_recovery: subpixel_conv
mae_finetune: 'False'
world_size: '8'
global_batch_size: '32'
experiment_dir: /home/jovyan/shared/dpp94/ssl-2dturb/BASE/BASE_seed_0_2phase_1000epochs
checkpoint_path_globstr: 
  /home/jovyan/shared/dpp94/ssl-2dturb/BASE/BASE_seed_0_2phase_1000epochs/training_checkpoints/ckpt_*.tar
best_checkpoint_path: 
  /home/jovyan/shared/dpp94/ssl-2dturb/BASE/BASE_seed_0_2phase_1000epochs/training_checkpoints/best_ckpt.tar
resuming: 'False'
local_rank: '0'
