[model]
in_channels = 2
d_embed = 128
n_heads = 8
n_layers = 8
img_shape = [ 256, 256,]
patch_shape = [ 8, 8,]
checkpoint_path = '/glade/derecho/scratch/jshen/pruning-turbulence-vit/patch_8/checkpoints/epoch_369.pt'

[train_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_ranges = [ [200000, 210000], [995000, 1004997], ]
target_offset = 3

[validation_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_ranges = [ [310000, 312000], ]
target_offset = 3

[pruning]
n_prune_iterations=8
prune_amount=0.1

[finetuning]
learning_rate = 0.0002
weight_decay = 1e-8
warmup_start_factor = 0.001
warmup_epochs = 1
plateau_factor = 0.2
plateau_patience = 3
epochs = 12
batch_size = 16
checkpoint_period = 2
output_dir = '/glade/derecho/scratch/jshen/pruning-turbulence-vit/'