#!/bin/bash

#PBS -N jshen
#PBS -A UCHI0014
#PBS -j oe
#PBS -k eod
#PBS -q main
#PBS -M jshe@uchicago.edu
#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=64:ngpus=4
#PBS -l gpu_type=a100

cd /glade/u/home/jshen/pruning-turbulence-vit/src

module load conda
module load cuda
conda activate vit

torchrun --standalone --nnodes=1 --nproc-per-node=4 script_train_distributed.py ./config/train/base_vit.toml
