checkpoint_file = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/model/best.tar"
output_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/prune_cosine_restarts/"

[model]
img_size = 256
patch_size = 4
tubelet_size = 2
in_chans = 2
encoder_embed_dim = 192
encoder_depth = 4
encoder_num_heads = 4
decoder_embed_dim = 96
decoder_depth = 4
decoder_num_heads = 4
mlp_ratio = 4.0
num_frames = 2
num_out_frames = 1
patch_recovery = "subpixel_conv"

[train_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_range = [ [200000, 210000], [995000, 1004998], ]
target_step = 3
stride = 1
num_frames = 2

[validation_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_range = [ [310000, 312000], ]
target_step = 3
stride = 1
num_frames = 2

[pruning]
prune_schedule = [0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06]
epoch_schedule = [  64,   64,   64,   64,   96,   96,   96,   96,  128,  128,  128]

[finetuning]
restart_optimizer = true
batch_size = 16
lr = 0.00002
weight_decay = 1e-8
warmup_start_factor = 0.01
num_warmup_epochs = 1
early_stop
